#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    https://shiny.posit.co/
#

library(shiny)
library(stringr)
library(shinyWidgets)
library(shinythemes)

# Define UI for application that draws a histogram
ui <- fluidPage(
  navbarPage("HITL AI Detector",
             tabPanel("Free version"),
             tabPanel("Pro Version (in development)")),
  
  theme = shinytheme("cyborg"),
  
    # Application title
    titlePanel("HITL AI Detector"),
  
    p("HITL AI detection software works by leveraging advanced algorithms and machine learning techniques to identify patterns and anomalies in data. It typically involves several stages: data collection, preprocessing, feature extraction, model training, and detection. Initially, the software gathers raw data from various sources, which is then cleaned and normalized during the preprocessing phase. In feature extraction, relevant characteristics or patterns are identified and extracted from the data. The extracted features are used to train a machine learning model, which learns to distinguish between normal and suspicious patterns based on historical data. Once trained, the model can analyze new data in real-time or batch mode, flagging potential issues or anomalies for further investigation. The software continuously learns and adapts, improving its accuracy over time as it is exposed to more data and feedback."),

    # Sidebar with a slider input for number of bins 
    sidebarLayout(
        sidebarPanel(
          textAreaInput("textAreaInput_1",
                        "paste your text here",
                        height = "300px",
                        value = "Sample text: Networking is a crucial aspect of both personal and professional growth. In the professional realm, effective networking can open doors to new job opportunities, collaborations, and partnerships. It involves building and maintaining relationships with individuals who can provide support, advice, and information relevant to your career."),
        radioButtons('radioButtons_1',
                    "Do you think this text was generated by AI?",
                    choices = c("Yes", "No"),
                    selected = NULL),
        sliderInput("sliderInput", 
                    "On a scale from 1 to 10, how confident are you?",
                    value = 5,
                    min = 0, max = 10)
        ),

        # Show a plot of the generated distribution
        mainPanel(
            actionButton('actionButton_1', "Generate report"),
            progressBar(id = "pb4", value = 0, display_pct = T),
            plotOutput("plot"),
            htmlOutput ("Percentage")
        )
    )
)

# Define server logic required to draw a histogram
server <- function(input, output, session) {
  
  vals <- reactiveValues()

  
  
  observeEvent(input$actionButton_1, {
    
    maxi <- 50
    for (i in 1:maxi) {
      updateProgressBar(session = session, id = "pb4", value = (i/maxi)*100)
      Sys.sleep(0.1)
    }
    
    output$plot <- renderPlot(
      boxplot(c(1:100))
    )
    
    output$Percentage <- renderText({  
      

      
      if (input$radioButtons_1 == "Yes") {
        str_glue("<font color=\"#FF0000\"><b> Yes! There is a {slider}% probability that the provided text is AI-generated </b></font>", 
                 slider = input$sliderInput * 10 + sample(c(1:9), 1) - 10)
      } else {
        str_glue("<font color=\"#00FF00\"><b> Most likely, this text is not generated by AI, but there is {slider}% probability that this text is AI-generated </b></font>",
                 slider = (10-input$sliderInput) * 10 + sample(c(1:9), 1) - 10)
      }
      
      })
  })
  


    
}

# Run the application 
shinyApp(ui = ui, server = server)
